In [3]:
%config IPCompleter.greedy=True

In [4]:
import numpy as np

In [5]:
my_list = [1,2,3,4]

In [6]:
my_list

[1, 2, 3, 4]

In [7]:
my_arr = np.array(my_list)

In [8]:
my_arr

array([1, 2, 3, 4])

In [9]:
my_list = [[1, 2, 3, 4],[5, 6, 7, 8], [1, 2, 3, 4]]

In [10]:
my_list

[[1, 2, 3, 4], [5, 6, 7, 8], [1, 2, 3, 4]]

In [11]:
my_arr = np.array(my_list)

In [12]:
my_arr # n x n matrix

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [13]:
arr = np.arange(0,11) # 0 to 10 print

In [14]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
arr = np.arange(0, 11, 2)

In [16]:
arr

array([ 0,  2,  4,  6,  8, 10])

In [17]:
arr = np.zeros(5) # 5 zeros

In [18]:
arr

array([0., 0., 0., 0., 0.])

In [19]:
arr = np.zeros((3,3)) # 3 X 3 2D Matrix

In [20]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
arr = np.ones(5)

In [22]:
arr

array([1., 1., 1., 1., 1.])

In [23]:
arr = np.ones((5,5)) # 5 X 5 2D array's of 1

In [24]:
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
type(arr) # n dimentional array

numpy.ndarray

In [26]:
np.ndim(arr) # how many dimention

2

In [27]:
arr.dtype # data type ex: 1. (is a floating number)

dtype('float64')

In [28]:
np.array([1,2,3], dtype='float64') # data type change to int to float 

array([1., 2., 3.])

In [29]:
np.linspace(1, 10, 4) # linierly spacing

array([ 1.,  4.,  7., 10.])

In [30]:
arr, spacing = np.linspace(0, 1, 3 , retstep = True) # return step = between space of two elements

In [31]:
arr

array([0. , 0.5, 1. ])

In [32]:
spacing

0.5

In [33]:
np.eye(4) # diagonally 1 . 4 X 4 matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [34]:
np.eye(4, k=1) # diagonal is right shift by 1

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [35]:
np.eye(4, k=-1) # diagonal is left shift by 1

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [36]:
np.random.rand(2) # it's gives u from 0 t0 1 and uniform distribution

array([0.298664  , 0.50062576])

In [37]:
np.random.rand(2,4) # it's gives u from 0 t0 1 and uniform distribution

array([[0.26140263, 0.54799583, 0.9425546 , 0.907435  ],
       [0.20486239, 0.38084213, 0.95021776, 0.96648675]])

In [38]:
np.random.randn(15) # it's gives u from -1 t0 1 and uniform distribution

array([-0.09532816, -1.40245166,  0.6751126 , -0.25996954, -0.93692939,
       -0.41855219, -1.06404296,  1.16979938, -0.06298182,  1.48679462,
        0.3322612 , -0.56497982,  0.27467377,  0.36264508,  1.19992845])

In [39]:
np.random.randint(0, 5) 

4

In [40]:
np.random.randint(0, 5) 

0

In [41]:
np.random.randint(0, 5) 

4

In [42]:
np.random.randint(0, 5) 

2

In [43]:
np.random.randint(0, 10, 10) 

array([3, 5, 1, 9, 4, 9, 3, 9, 4, 1])

In [44]:
np.random.randint(0, 100, (3,4)) # random 3 X 3 matrix

array([[84, 21, 89, 71],
       [60, 92, 93, 75],
       [10, 11, 84, 29]])

In [45]:
np.random.seed(43) # produce a result again and again
np.random.randint(0, 10, 7) 

array([4, 0, 1, 5, 0, 3, 1])

In [46]:
np.random.randint(0, 10, 7) 

array([2, 7, 0, 3, 2, 9, 1])

In [47]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [48]:
arr.max()

24

In [49]:
arr.reshape(5,5) 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [50]:
np.arange(25).reshape(5,5) # it same as arr.reshape(5,5) 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [51]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [52]:
arr.argmax() # find max value index

24

In [53]:
arr.shape

(25,)

# arr reshape by 25 X 1

In [54]:
arr.reshape(25,1) # arr reshape by 25 X 1

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [55]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [56]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [57]:
arr[0:10:2] # print 0 to 10 and index incresaed by 2

array([0, 2, 4, 6, 8])

In [58]:
arr_slice = arr[0:10]

In [59]:
arr_slice 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
arr_slice[:] = 0 

In [61]:
arr_slice

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# arr_slice is a pointer (referance) that updates the value into the actual array..

In [62]:
arr # arr_slice is a pointer (referance) that updates the value into the actual array..

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

# MATRIX OPERAION

In [63]:
mat = np.arange(0,25).reshape(5,5)

In [64]:
mat

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [65]:
mat[0] # row 0

array([0, 1, 2, 3, 4])

In [66]:
mat[0][0] # row 0 , colum 0

0

In [67]:
mat[:][4] # colum 4

array([20, 21, 22, 23, 24])

In [68]:
mat[:2,:2] # row 0 upto 2 , colum 0 upto 2

array([[0, 1],
       [5, 6]])

In [69]:
mat[:3,:3] # row 0 upto 3 , colum 0 upto 3

array([[ 0,  1,  2],
       [ 5,  6,  7],
       [10, 11, 12]])

In [70]:
mat[2,2]

12

In [74]:
mat = np.zeros((10,10))

In [75]:
mat

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [77]:
for i in range(mat.shape[1]):
    mat[i] = i # row has been changed coresponding it's row number

In [78]:
mat

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [79]:
mat[[1,3,5,6]] # specific row no print

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.]])

In [81]:
arr = np.arange(0,11)

In [82]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [83]:
arr > 2 # setisfying the condition

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True])

In [84]:
filter = arr > 3

In [85]:
arr[filter] # everything is greater than filter

array([ 4,  5,  6,  7,  8,  9, 10])

In [86]:
arr = np.arange(0,11)

In [87]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [88]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [89]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [90]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [91]:
np.square(arr)

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [92]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [93]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [94]:
np.log(arr) # log 0, log 1,log 2, log 3

C:\Users\ASUS\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [95]:
np.max(arr)

10

In [96]:
mat_1 = np.array([[1,2,3],[4,5,6]])

In [97]:
mat_2 = np.array([[3,2,1],[6,5,4]])

In [98]:
mat_1

array([[1, 2, 3],
       [4, 5, 6]])

In [99]:
mat_2

array([[3, 2, 1],
       [6, 5, 4]])

In [100]:
mat_1 + mat_2

array([[ 4,  4,  4],
       [10, 10, 10]])

In [101]:
np.add(mat_1 , mat_2)

array([[ 4,  4,  4],
       [10, 10, 10]])

In [102]:
np.subtract(mat_1 , mat_2)

array([[-2,  0,  2],
       [-2,  0,  2]])

In [103]:
np.multiply(mat_1 , mat_2)

array([[ 3,  4,  3],
       [24, 25, 24]])

In [105]:
np.divide(mat_1 , mat_2)

array([[0.33333333, 1.        , 3.        ],
       [0.66666667, 1.        , 1.5       ]])

In [106]:
np.sum(mat_1 , axis = 0) # [[1,2,3],[4,5,6]] = [1+4,2+5,3+6]

array([5, 7, 9])

In [110]:
v = np.array([9,10])
w = np.array([11,12])

In [111]:
# dot product in two vector
# (9*11 + 10*12) = 219
v.dot(w) 

219

In [112]:
w.dot(v)

219

In [114]:
mat_1

array([[1, 2, 3],
       [4, 5, 6]])

In [113]:
mat_1.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [124]:
arr = np.arange(50).reshape(5,10)

In [125]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [127]:
arr.reshape(10,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])